ci: re-enable TDX build and tests (#102)
* ci: re-enable TDX build and tests

* fix(tdx azure): adapt for Azure TDX

* fix: filter test on Ansible

* fix: missing VM_SIZE on Azure packer build

* Fix: bump tee-tools with buf fixes for Azure

* Fix: bump base64 to ^0.22 and update tee-tools

* [CI] Fix: temporary allow failure for cargo-deny job

* Fix: bump tee-tools with bug fixes for GCP TDX

* Add: install libtdx-attest-dev in Cosmian VM powered by Ubuntu

* fix: adapt license for tdx-attest-* crates

* test: both SEV and TDX

* chore(azure): create image definition for TDX and SEV

* fix: install libtdx-attest both on Ubuntu and RHEL since cosmian_vm_agent depends on it

* fix: change cryptsetup parameter size

* fix: reboot after TPM support install

* fix: verify cosmian_vm hash before using it

* fix(ansible): compute cosmian_vm hash

* chore: revert some changes

* fix: read luks password when checking agent

* fix(mount_luks): attach device only if exists

* fix: reboot after TPM support install

* fix: use tee-tools from tag 1.4.0

---------

Co-authored-by: grydz <grydz@pm.me>

diff --git a/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool b/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
--- a/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
+++ b/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
@@ -108,7 +108,7 @@ echo "Creating a $CONTAINER_SIZE container..."
 fallocate -l "$CONTAINER_SIZE" "$CONTAINER_PATH"
 
 # Encrypt the container (a password is required to run this command)
-echo "Encrypting the container (with password=$PASSWORD)..."
+echo "Encrypting the container (with password=${PASSWORD})..."
 echo -n "$PASSWORD" | cryptsetup luksFormat "$CONTAINER_PATH" -d -
 
 # Open the container and map it (a password is required to run this command)
@@ -120,7 +120,7 @@ echo "Formatting the container in Ext4..."
 mkfs -t ext4 "$CONTAINER_MAPPING_PATH"
 
 # Mount it
-echo "Mouting the container at $CONTAINER_MOUNT_PATH..."
+echo "Mounting the container at $CONTAINER_MOUNT_PATH..."
 mkdir -p "$CONTAINER_MOUNT_PATH"
 mount "$CONTAINER_MAPPING_PATH" "$CONTAINER_MOUNT_PATH"
 
@@ -134,7 +134,19 @@ fi
 
 # Enroll the TPM to decrypt the luks without password (a password is required to run this command)
 # Details on PCRs: https://uapi-group.org/specifications/specs/linux_tpm_pcr_registry/
-echo "Enrolling the TPM for this container..."
+echo "Enrolling the TPM for this container on block device $BLOCK_DEVICE..."
+
+set +e
 PASSWORD=$PASSWORD systemd-cryptenroll --tpm2-device=auto --wipe-slot=tpm2 "$BLOCK_DEVICE"
+if [ $? -ne 0 ]; then
+    # Need to clean container after failure
+    rm -f "$CONTAINER_PATH"
+    exit 1
+fi
+
+# Display debug information
+set -x
+cryptsetup luksDump $CONTAINER_PATH
+set +x
 
 echo "Process completed with success!"
