fix: reboot problem and add KMS installation via Ansible (#84)
* fix: use PCRs 7 and 11 + Ansible lints

* feat: rust cache GH optim

* test: re-add rhel - simple test

* feat: add mount luks service

* chore: rename supervisor cosmian vm conf

* fix: increase timeout after reboot

* fix: remove PCR 7

* feat: create bash script for GCP image tests

* feat: prepare KMS packer files

* chore: update initrd afer modifiying crypttab

* fix: ansible deployment

* fix: ansible KMS deployment

* feat: add packer for KMS

* fix: build

* feat: parametrize gcp_image.yml for product

* ci: add luks mount option

* fix: KMS GCP tests

* feat: add autostart in manual installations

* test: small test on rhel

* ci: run cosmian_kms in startup-script

* fix: missing network tag

* fix: network tags

* fix: shell with set -e

* fix: disable GCP VM autoremove

* fix: let VM autodestroy in the next 10 hours

* fix: do not delete VM

* fix(ansible): enable nginx and redis service on KMS

* fix: call app init

* fix: retrieve IP_ADDR before KMS tests

* fix: KMS reset count

* test: re-enable rhel GCP build (#86)

* fix: re-add RHEL and comment remove GCP image task

* feat(ansible): Run cosmian vm locally (#87)

* fix: add check on confidential VM and post test on cosmian vm availability

* fix: play kms on Azure/GCP + reboot OK

* fix: variabilize VM and KMS versions in CI and packer (#88)

* fix: revert ssh_timeout

* feat: templatize hcl and merge them

* Fix: use clevis instead of systemd-cryptenroll/systemd-cryptsetup

* Fix: add headless=true option to /etc/crypttab

* Fix: try to use systemd-cryptenroll and clevis

* [CI] Fix: jobs name for GH Actions

* [CI] Fix: increment timeout and remove KMS for now

* Fix: use clevis instead of systemd-cryptenroll/systemd-cryptsetup

* fix: KMS deployment on RHEL

* fix: bypass for now the HTTPS test nginx connection on RHEL

* fix: remove PCR 7

* fix: run nginx with nginx/www-data user depending on distrib

* fix: tests

* fix: revert change on mount luks service

* fix: bypass nginx tests for now

---------

Co-authored-by: grydz <grydz@pm.me>

diff --git a/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool b/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
--- a/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
+++ b/ansible/roles/cosmian_vm_agent/templates/cosmian_fstool
@@ -1,6 +1,6 @@
 #!/usr/bin/bash
 
-set -e
+set -ex
 
 usage() {
     echo "Usage: $0 --size <> [--location <>] [--password <>]"
@@ -41,25 +41,25 @@ parse_args() {
     # Parse args
     while [[ $# -gt 0 ]]; do
         case $1 in
-            --size)
+        --size)
             CONTAINER_SIZE="$2"
             shift # past argument
             shift # past value
             ;;
 
-            --location)
+        --location)
             CONTAINER_PATH="$2"
             shift # past argument
             shift # past value
             ;;
 
-            --password)
+        --password)
             PASSWORD="$2"
             shift # past argument
             shift # past value
             ;;
 
-            -*)
+        -*)
             usage
             ;;
         esac
@@ -128,22 +128,16 @@ mount "$CONTAINER_MAPPING_PATH" "$CONTAINER_MOUNT_PATH"
 BLOCK_DEVICE=$(losetup -ln --raw -O NAME,BACK-FILE | grep "$CONTAINER_PATH" | cut -f1 -d" ")
 
 if [ -z "$BLOCK_DEVICE" ]; then
-    echo "Can't find the bloc device attached to $CONTAINER_PATH"
+    echo "Can't find the block device attached to $CONTAINER_PATH"
     exit 1
 fi
 
 # Enroll the TPM to decrypt the luks without password (a password is required to run this command)
+# Details on PCRs: https://uapi-group.org/specifications/specs/linux_tpm_pcr_registry/
 echo "Enrolling the TPM for this container..."
-PASSWORD=$PASSWORD systemd-cryptenroll --tpm2-device=/dev/tpmrm0 "$BLOCK_DEVICE"
+PASSWORD=$PASSWORD systemd-cryptenroll --tpm2-device=auto --wipe-slot=tpm2 "$BLOCK_DEVICE"
+echo -n "$PASSWORD" | clevis luks bind -d "$CONTAINER_PATH" -k - tpm2 '{"pcr_bank":"sha256"}'
 
-# Remove previous entry from the fstab and crypttab (create a .bak file to ease the rollback)
-echo "Removing previous obsolete auto mounting rules..."
-sed -i.bak "/$CONTAINER_MAPPING_NAME/d" /etc/crypttab
-sed -i.bak "/$CONTAINER_MAPPING_NAME/d" /etc/fstab
-
-# Auto decrypt & auto mount the luks when rebooting (if not already done)
-echo "Enabling auto mounting when rebooting..."
-grep -qF -- "$CONTAINER_MAPPING_NAME $CONTAINER_PATH" /etc/crypttab || echo "$CONTAINER_MAPPING_NAME $CONTAINER_PATH none tpm2-device=auto" >> /etc/crypttab
-grep -qF -- "$CONTAINER_MAPPING_PATH $CONTAINER_MOUNT_PATH" /etc/crypttab || echo "$CONTAINER_MAPPING_PATH $CONTAINER_MOUNT_PATH ext4 defaults 0 0" >> /etc/fstab
+dracut -fv --regenerate-all
 
 echo "Process completed with success!"
