Fix: use system-cryptenroll again but use container instead of block device

diff --git a/resources/scripts/cosmian_fstool b/resources/scripts/cosmian_fstool
--- a/resources/scripts/cosmian_fstool
+++ b/resources/scripts/cosmian_fstool
@@ -125,18 +125,18 @@ mkdir -p "$CONTAINER_MOUNT_PATH"
 mount "$CONTAINER_MAPPING_PATH" "$CONTAINER_MOUNT_PATH"
 
 # Determine the block device
-BLOCK_DEVICE=$(losetup -ln --raw -O NAME,BACK-FILE | grep "$CONTAINER_PATH" | cut -f1 -d" ")
+# BLOCK_DEVICE=$(losetup -ln --raw -O NAME,BACK-FILE | grep "$CONTAINER_PATH" | cut -f1 -d" ")
 
-if [ -z "$BLOCK_DEVICE" ]; then
-    echo "Can't find the block device attached to $CONTAINER_PATH"
-    exit 1
-fi
+# if [ -z "$BLOCK_DEVICE" ]; then
+#     echo "Can't find the block device attached to $CONTAINER_PATH"
+#     exit 1
+# fi
 
 # Enroll the TPM to decrypt the luks without password (a password is required to run this command)
 # Details on PCRs: https://uapi-group.org/specifications/specs/linux_tpm_pcr_registry/
 echo "Enrolling the TPM for this container..."
-# PASSWORD=$PASSWORD systemd-cryptenroll --tpm2-device=auto  "$BLOCK_DEVICE"
-echo -n "$PASSWORD" | clevis luks bind -d "$CONTAINER_PATH" -k - tpm2 '{}'
+PASSWORD=$PASSWORD systemd-cryptenroll --tpm2-device=auto  "$CONTAINER_PATH"
+# echo -n "$PASSWORD" | clevis luks bind -d "$CONTAINER_PATH" -k - tpm2 '{}'
 
 # Remove previous entry from the fstab and crypttab (create a .bak file to ease the rollback)
 echo "Removing previous obsolete auto mounting rules..."
@@ -145,7 +145,7 @@ sed -i.bak "/$CONTAINER_MAPPING_NAME/d" /etc/fstab
 
 # # Auto decrypt & auto mount the luks when rebooting (if not already done)
 echo "Enabling auto mounting when rebooting..."
-grep -qF -- "$CONTAINER_MAPPING_NAME $CONTAINER_PATH" /etc/crypttab || echo "$CONTAINER_MAPPING_NAME $CONTAINER_PATH - tpm2-device=auto,headless=true" >>/etc/crypttab
+grep -qF -- "$CONTAINER_MAPPING_NAME $CONTAINER_PATH" /etc/crypttab || echo "$CONTAINER_MAPPING_NAME $CONTAINER_PATH - tpm2-device=/dev/tpmrm0,headless=true" >>/etc/crypttab
 grep -qF -- "$CONTAINER_MAPPING_PATH $CONTAINER_MOUNT_PATH" /etc/crypttab || echo "$CONTAINER_MAPPING_PATH $CONTAINER_MOUNT_PATH ext4 defaults 0 0" >>/etc/fstab
 
 dracut -fv --regenerate-all
