[CI] Fix: retry with ima-setup on RHEL

diff --git a/ansible/roles/configure_ima/tasks/main.yml b/ansible/roles/configure_ima/tasks/main.yml
--- a/ansible/roles/configure_ima/tasks/main.yml
+++ b/ansible/roles/configure_ima/tasks/main.yml
@@ -14,9 +14,9 @@
   register: configure_ima_etc_default_grub
   tags: update_grub
 
-- name: Configure IMA on Rocky Linux
+- name: Configure IMA on RHEL
   when: ansible_distribution_file_variety == 'RedHat'
-  tags: ima_rocky
+  tags: ima_rhel
   block:
     - name: Install packages to configure IMA
       ansible.builtin.dnf:
@@ -64,6 +64,44 @@
         executable: /bin/bash
       changed_when: true
 
+    - name: Setup IMA policy for RHEL
+      when: ansible_distribution == 'RedHat'
+      ansible.builtin.shell: |
+        ima-setup --policy=/usr/share/ima/policies/03-cosmian-remote-attestation
+      args:
+        executable: /bin/bash
+      changed_when: true
+      ignore_errors: true
+      become: true
+      register: configure_ima_errors_register
+
+    # - name: Setup IMA policy for RHEL
+    #   ansible.builtin.shell: |
+    #     # extracted from /usr/bin/ima-setup script
+    #     IMA_SYSTEMD_POLICY=/etc/ima/ima-policy
+    #     IMA_POLICY_SYSFS=/sys/kernel/security/ima/policy
+    #     ima_policy_path=/usr/share/ima/policies/03-cosmian-remote-attestation
+    #     if ! test -f "$ima_policy_path"; then
+    #             echo "$ima_policy_path doesn't exist"
+    #             return 1
+    #     fi
+    #     if ! echo "$ima_policy_path" >"$IMA_POLICY_SYSFS"; then
+    #             echo "$ima_policy_path can't be loaded"
+    #             return 1
+    #     fi
+    #     # Let systemd load the IMA policy which will load LSM rules first so IMA
+    #     # policy containing rules like "appraise obj_type=ifconfig_exec_t" can be
+    #     # loaded
+    #     [[ -e /etc/ima ]] || mkdir -p /etc/ima/
+    #     if ! cp --preserve=xattr "$ima_policy_path" "$IMA_SYSTEMD_POLICY"; then
+    #             echo "Failed to copy $ima_policy_path to $IMA_SYSTEMD_POLICY"
+    #             return 1
+    #     fi
+    #   args:
+    #     executable: /bin/bash
+    #   changed_when: true
+    #   become: true
+
     - name: Re-label the whole system
       ansible.builtin.command:
         cmd: |
@@ -97,44 +135,6 @@
       ansible.builtin.command: setsebool -P httpd_can_network_connect 1
       changed_when: true
 
-    # - name: Setup IMA policy for RHEL
-    #   when: ansible_distribution == 'RedHat'
-    #   ansible.builtin.shell: |
-    #     ima-setup --policy=/usr/share/ima/policies/03-cosmian-remote-attestation
-    #   args:
-    #     executable: /bin/bash
-    #   changed_when: true
-    #   ignore_errors: true
-    #   become: true
-    #   register: configure_ima_errors_register
-
-    - name: Setup IMA policy for Rocky
-      ansible.builtin.shell: |
-        # extracted from /usr/bin/ima-setup script
-        IMA_SYSTEMD_POLICY=/etc/ima/ima-policy
-        IMA_POLICY_SYSFS=/sys/kernel/security/ima/policy
-        ima_policy_path=/usr/share/ima/policies/03-cosmian-remote-attestation
-        if ! test -f "$ima_policy_path"; then
-                echo "$ima_policy_path doesn't exist"
-                return 1
-        fi
-        if ! echo "$ima_policy_path" >"$IMA_POLICY_SYSFS"; then
-                echo "$ima_policy_path can't be loaded"
-                return 1
-        fi
-        # Let systemd load the IMA policy which will load LSM rules first so IMA
-        # policy containing rules like "appraise obj_type=ifconfig_exec_t" can be
-        # loaded
-        [[ -e /etc/ima ]] || mkdir -p /etc/ima/
-        if ! cp --preserve=xattr "$ima_policy_path" "$IMA_SYSTEMD_POLICY"; then
-                echo "Failed to copy $ima_policy_path to $IMA_SYSTEMD_POLICY"
-                return 1
-        fi
-      args:
-        executable: /bin/bash
-      changed_when: true
-      become: true
-
     - name: Reboot
       ansible.builtin.reboot:
         reboot_command: systemctl reboot
@@ -160,7 +160,6 @@
         owner: root
         group: root
         mode: u=rwX,g=rX,o=rX
-
 
     - name: Copy the bash script to modify grub conf
       when: configure_ima_etc_default_grub.stat.exists
